language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run docs:build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_TOKEN
  local_dir: dist-docs
  on:
    branch: master
